### ISSUE TITLE
Explore API Gateway Proxy Integration

### ISSUE THREAD

**Issue by tjkemper** [KemperIO/slack-riddle#2]
[Configure Proxy Integration for a Proxy Resource](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-proxy-resource?icmpid=docs_apigateway_console)

**Comment by akjams** [comment]
Looks like you are already using lambda proxy integration in /getRiddle

**Comment by akjams** [comment]
but if you meant using the RequestStreamHandler then dibs! I'm making an example with an AnswerHandler that will return riddle answers given id

**Comment by tjkemper** [comment]
@austinkemper 

Looks like [RequestHandler2](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/handlers/RequestHandler2.html) deprecates `RequestHandler`.

Also looks like [RequestStreamHandler](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestStreamHandler.java) is low level.
